apiVersion: apps/v1
kind: Deployment
metadata:
  name:  book-api
  namespace: default
  labels:
    app:  book-api
spec:
  selector:
    matchLabels:
      app: book-api
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  book-api
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  book-api
        image:  tapiwanashembizvo/book_api_image:latest

        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        env:
        - name: DB_HOST_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST_NAME


        - name: DB_BANE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_BANE

        - name: DB_APP_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_APP_USER

        - name: DB_APP_USER_PWD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_APP_USER_PWD

        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PORT
              
        ports:
        - containerPort:  8080
          name:  book-api
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always